### ISSUE TITLE
Feature Request: Add the ability to hide attributes.

### ISSUE THREAD

**Issue by julianrinaldi** [jeremywillans/lovelace-roomba-vacuum-card#6]
It would be great to be able to hide attributes on the Roomba card. Currently there are a few attributes that are of no use to me, especially since I'm using it for a Braava Jet M6 and not a vacuum.

**Comment by bakasaru** [comment]
Customization would be handy. For now I just obfuscated the clean_base and Evacs attributes -
![braava](https://user-images.githubusercontent.com/13490776/111045104-3db46b80-8401-11eb-90a4-e7a99f4ed51b.png)

**Comment by julianrinaldi** [comment]
Looks great. Could you share your code and graphics?

**Comment by bakasaru** [comment]
Haven't worked through all the permutations of state but this should get you started.
Modified template sensor from base package for mop (rest980_2) and vacuum (rest980). Added "pad" and "tank" attributes which are then referenced in the custom card for the mop to replace clean_base and evacs. Added clean_mode to both mop and vacuum sensors, which is the secondary icon in the upper right of the card, otherwise safe to ignore:
```YAML
- platform: template
  sensors:
    mop:
      .
      .
      .
      attribute_templates:
      ...
        pad: >-
          {% set mapper = {
            'reusableDry' : 'Dry',
            'reusableWet' : 'Wet',
            'disposableDry' : 'Single Dry',
            'disposableWet' : 'Single Wet'
            } %}
          {% set state = state_attr('sensor.rest980_2', 'detectedPad') %}
          {{ mapper[state] if state in mapper else state}}
        clean_mode: >-
          {% set state = state_attr('sensor.rest980_2', 'padWetness')['disposable'] %}
          {{ state }}
        tank: >-
          {% if state_attr('sensor.rest980_2', 'mopReady')['tankPresent'] and state_attr('sensor.rest980_2', 'mopReady')['lidClosed'] %}
            Ready
          {% elif state_attr('sensor.rest980_2', 'mopReady')['tankPresent'] and (state_attr('sensor.rest980_2', 'mopReady')['lidClosed'] == false) %}
            Lid Open
          {% else %}
            Fill Tank
          {% endif %}
        ...
```
similarly for the vacuum package, duplicating custom clean_mode attribute, again only for customization of the secondary info/icon. Unfortunately could not see further attribute changes when changing between auto, single or dual pass (this for the i7+):
```YAML
- platform: template
  sensors:
    vacuum:
      .
      .
      .
      attribute_templates:
        clean_mode: >-
          {% set state = state_attr('sensor.rest980', 'noAutoPasses') %}
          {% set mapper = {
            true: 2,
            false: 1 } %}
          {{ mapper[state] if state in mapper else state }}
```
modified the custom roomba card to work for both mop/vaccuum. This and the changes to getMaintStatus just provide a custom secondary icon in the upper right, while also changing the default maintenance check icon to mdi:progress-wrench.  Ignore this and the next to leave the maintenance icon/status as defaults (roomba-vacuum-card.js):
```js
...
- ${this.state.showMaint ?
  html`<div class="title-right" style="${this.style.text}" @click="${() => this.fireEvent('hass-more-info')}"><ha-icon icon="mdi:wrench" style="padding-bottom: 5px"></ha-icon> <ha-icon icon="${this.getMaintStatus('icon')}" style="padding-bottom: 5px; color:${this.getMaintStatus('color')}"></ha-icon></div>` : null}
+ ${this.state.showMaint ?
  html`<div class="title-right" style="${this.style.text}" @click="${() => this.fireEvent('hass-more-info')}"><ha-icon icon="${this.getMaintStatus('clean_mode')}" style="padding-bottom: 5px; color: #329FE6"></ha-icon> <ha-icon icon="${this.getMaintStatus('icon')}" style="padding-bottom: 5px; color:${this.getMaintStatus('color')}"></ha-icon></div>` : null}
```
and hack of getMaintStatus so as to distinguish between mop and vacuum for secondary info:
```js
      getMaintStatus(field) {
        const re = new RegExp("(True|true)");
        switch(field) {
          case "clean_mode":
            if (`${this.state.name}` == "Meredith") {
              switch(this.stateObj.attributes['clean_mode']) {
                case 1:
                  return `mdi:water-minus`;
                case 2:
                  return `mdi:water`;
                case 3:
                  return `mdi:water-plus`;
                default:
                  return ``;
              }
            } else {
              switch(this.stateObj.attributes['clean_mode']) {
                case 1:
                  return `mdi:plus-circle-multiple`;
                case 2:
                  return `mdi:checkbox-multiple-blank-circle`;
              }
            }
            break;
          case "icon":
            if (re.test(this.stateObj.attributes['maint_due'])) {
              return `mdi:alert`;
            } else {
              return `mdi:progress-wrench`;
            }
          ...
```
Then in the custom card yaml for the mop to overwrite the clean_base and evac_events:
```YAML
- type: "custom:roomba-vacuum-card"
  entity: sensor.mop
  image: "/local/mop.png"
  attributes:
    clean_base: tank
    evac_events: pad
  buttons: false
  labels:
    clean_base: Tank
    evac_events: Pad
```
Here's the blank mop image for the card (mop.png in /config/www/):
![mop](https://github.com/bakasaru/ha_stuff/raw/main/mop.png)
HTH

**Comment by julianrinaldi** [comment]
The recent update has taken care of this!  Thanks!

**Comment by clipse2004** [comment]
Hey did you get this working? Please can you share your yaml?

In the log i got this error:
`2021-07-01 22:16:42 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'disposable' when rendering '{% set state = state_attr('sensor.rest980_2', 'padWetness')['disposable'] %} {{ state }}'
2021-07-01 22:16:42 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'None' has no attribute 'tankPresent' when rendering '{% if state_attr('sensor.rest980_2', 'mopReady')['tankPresent'] and state_attr('sensor.rest980_2', 'mopReady')['lidClosed'] %}
  Ready
{% elif state_attr('sensor.rest980_2', 'mopReady')['tankPresent'] and (state_attr('sensor.rest980_2', 'mopReady')['lidClosed'] == false) %}
  Lid Open
{% else %}
  Fill Tank
{% endif %}'
  Ready
{% elif state_attr('sensor.rest980_2', 'mopReady')['tankPresent'] and (state_attr('sensor.rest980_2', 'mopReady')['lidClosed'] == false) %}
  Lid Open
{% else %}
  Fill Tank
{% endif %}'`

thanks a lot

**Comment by julianrinaldi** [comment]
Literally finally just got this working today. There is a part missing from the directions. You need to find this sensor and add the last three json attributes.

```
- platform: rest
  name: rest980
  json_attributes:
    - batPct
    - bin
    - cleanMissionStatus
    - dock
    - pose
    - signal
    - bbmssn
    - bbrun
    - name
    - pmaps
    - softwareVer
    - detectedPad
    - padWetness
    - mopReady
  resource: !secret vacuum_state
  value_template: 'OK'
  scan_interval: 10
```
